parameters:
  extensions: []

steps:
- ${{ each ext in parameters.extensions }}:
  - task: DownloadPipelineArtifact@2
    displayName: Retrieve tree-sitter-dyn.${{ ext }}
    inputs:
      artifact: tree-sitter-dyn.${{ ext }}
      path: $(System.DefaultWorkingDirectory)
