[package]
name = "emacs-tree-sitter"
version = "0.1.0"
authors = ["Tuấn-Anh Nguyễn <ubolonton@gmail.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"
name = "tree_sitter_dyn"
crate-type = ["cdylib"]

[dependencies]
emacs = "0.10.2"
libloading = "0.5.1"

[dependencies.tree-sitter]
version = "0.3.10"
git = "https://github.com/ubolonton/tree-sitter"
branch = "rust-binding"

[profile.release]
opt-level = 3
lto = "thin"
