steps:
- powershell: |
    $bundle_version = ((cask eval "(progn (require 'tree-sitter-langs) (princ tree-sitter-langs--version))") | Out-String).Trim()
    echo "##vso[task.setvariable variable=BUNDLE_VERSION]$bundle_version"
    cask eval "(progn (require 'tree-sitter-langs) (tree-sitter-langs-create-bundle))"
  name: create_grammar_bundle
  displayName: Create grammar bundle (Windows)
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

- bash: |
    BUNDLE_VERSION=$(cask eval "(progn (require 'tree-sitter-langs) (princ tree-sitter-langs--version))")
    echo "##vso[task.setvariable variable=BUNDLE_VERSION]$BUNDLE_VERSION"
    cask eval "(progn (require 'tree-sitter-langs) (tree-sitter-langs-create-bundle))"
  displayName: Create grammar bundle
  condition: and(succeeded(), ne(variables['Agent.OS'], 'Windows_NT'))
