parameters:
  oses: []

steps:

# TODO: Set $BUNDLE_VERSION from a previous job instead. Or even better, use
# Emacs Lisp to upload the files, instead of a bash script.
- bash: |
    set -e
    BUNDLE_VERSION=$(cask eval "(progn (require 'tree-sitter-langs-build) (princ tree-sitter-langs--bundle-version))")
    echo "##vso[task.setvariable variable=BUNDLE_VERSION]$BUNDLE_VERSION"
  workingDirectory: langs

- ${{ each os in parameters.oses }}:
  - task: DownloadPipelineArtifact@2
    displayName: Retrieve tree-sitter-grammars-${{ os }}-$(BUNDLE_VERSION).tar.gz
    inputs:
      artifact: tree-sitter-grammars-${{ os }}
      path: langs
  - bash: ./bin/upload-to-bintray
    # TODO: Publish as well, instead of having to do so manually afterwards.
    displayName: Upload tree-sitter-grammars bundles to bintray os=${{ os }}
    env:
      BINTRAY_API_KEY: $(BINTRAY_API_KEY)
      BINTRAY_PKG: tree-sitter-grammars
      BINTRAY_LOCAL_PATH: langs/tree-sitter-grammars-${{ os }}-$(BUNDLE_VERSION).tar.gz
      BINTRAY_REMOTE_PATH: tree-sitter-grammars-${{ os }}-$(BUNDLE_VERSION).tar.gz
