# baseURL = "http://ubolonton.github.io/emacs-tree-sitter/"
languageCode = "en-us"
title = "Emacs Tree-sitter"

googleAnalytics = "UA-138609797-2"

relativeURLs = true

theme = [
  "docdock",
  # "learn",
  # "alabaster",
  # "hugo-bare-min-theme",
  # "techdoc",

  # "docsy",
  # "book",
  # "docuapi",
]

[markup.highlight]
# style = "github"
noClasses = false

[params]
themeStyle = "original"

[outputs]
home = [ "HTML", "RSS", "JSON"]
