trigger:
- grammar-bundle

pr: none

resources:
  repositories:
  - repository: emacs-module-rs
    type: github
    name: ubolonton/emacs-module-rs
    ref: azure-pipelines
    endpoint: ubolonton

jobs:
- job: Build
  pool:
    vmImage: $(IMAGE_NAME)
  strategy:
    matrix:
      vs2017-win2016:
        IMAGE_NAME: 'vs2017-win2016'
        BUNDLE_OS: windows
      macos-10.14-emacs-25.3:
        IMAGE_NAME: 'macos-10.14'
        EVM_EMACS: emacs-25.3
        BUNDLE_OS: macos
      ubuntu-16.04-emacs-25.3:
        IMAGE_NAME: 'ubuntu-16.04'
        EVM_EMACS: emacs-25.3
        BUNDLE_OS: linux
  steps:
  - template: .azure-pipelines/steps/setup-emacs.yml@emacs-module-rs
  - template: .azure-pipelines/steps/setup-cask.yml@emacs-module-rs
  - template: steps/setup-tree-sitter-cli.yml
  - template: steps/grammar-bundle/-create.yml
  - template: steps/grammar-bundle/-save.yml

- job: Publish
  dependsOn: Build
  pool:
    vmImage: macos-10.14
  variables:
    EVM_EMACS: emacs-26.3
  steps:
  - template: .azure-pipelines/steps/setup-emacs.yml@emacs-module-rs
  - template: .azure-pipelines/steps/setup-cask.yml@emacs-module-rs
  - template: steps/grammar-bundle/-upload.yml
    parameters:
      oses:
      - windows
      - macos
      - linux
