trigger:
- master
- ci

pr:
- master

strategy:
  matrix:
    vs2017-win2016:
      IMAGE_NAME: 'vs2017-win2016'
    # windows-2019:
    #   IMAGE_NAME: 'windows-2019'

    macos-10.14-emacs-25.3:
      IMAGE_NAME: 'macos-10.14'
      EVM_EMACS: emacs-25.3
    macos-10.14-emacs-26.3:
      IMAGE_NAME: 'macos-10.14'
      EVM_EMACS: emacs-26.3
    # Emacs is getting "Killed 9" on these agents, probably due to macOS 10.15 updates.
    # macos-10.15-emacs-25.3:
    #   IMAGE_NAME: 'macos-10.15'
    #   EVM_EMACS: emacs-25.3
    # macos-10.15-emacs-26.3:
    #   IMAGE_NAME: 'macos-10.15'
    #   EVM_EMACS: emacs-26.3

    ubuntu-16.04-emacs-25.3:
      IMAGE_NAME: 'ubuntu-16.04'
      EVM_EMACS: emacs-25.3
    ubuntu-18.04-emacs-25.3:
      IMAGE_NAME: 'ubuntu-18.04'
      EVM_EMACS: emacs-25.3
    ubuntu-18.04-emacs-26.3:
      IMAGE_NAME: 'ubuntu-18.04'
      EVM_EMACS: emacs-26.3

pool:
  vmImage: $(IMAGE_NAME)

resources:
  repositories:
  - repository: emacs-module-rs
    type: github
    name: ubolonton/emacs-module-rs
    ref: azure-pipelines
    endpoint: ubolonton

steps:
- template: .azure-pipelines/steps/setup-rust.yml@emacs-module-rs
- template: .azure-pipelines/steps/setup-llvm.yml@emacs-module-rs
- template: .azure-pipelines/steps/setup-emacs.yml@emacs-module-rs
- template: .azure-pipelines/steps/setup-cask.yml@emacs-module-rs
- template: steps/-build.yml
- template: steps/setup-tree-sitter-cli.yml
- template: steps/-test.yml
