trigger:
- master
- azure-pipelines

pr:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- template: steps/install-rust.yml
- template: steps/set-up-llvm.yml
- template: steps/-build.yml
- template: steps/install-emacs.yml
- template: steps/set-up-tree-sitter-cli.yml
- template: steps/-test.yml
